from .MLP       import *
from .LeNet300       import *
from .SMLP       import *
from .SLeNet300       import *
from .LeNet5       import *
from .SLeNet5       import *
from .VGG       import *
from .SVGG       import *
from .ResNet       import *
from .SResNet       import *
